name: CI/CD
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, edited, closed]
  push:
    branches: [ master, action_logs ]

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        consul_acl: ["consul_acl_enabled", "consul_acl_disabled"]
        consul_acl_default_policy: ["consul_acl_deny"]
        nomad_acl: ["nomad_acl_enabled", "nomad_acl_disabled"]
        hashicorp_binary: ["hashicorp_oss", "hashicorp_enterprise"]

    steps:
      - uses: actions/checkout@v2

      - name: set consul acl (enabled/disabled)
        id: consul_acl
        run: |
          if [ "$test_consul_acl" == 'consul_acl_enabled' ]
          then
              echo "::set-output name=consul_acl::true"
          else
              echo "::set-output name=consul_acl::false"
          fi
        env:
          test_consul_acl: ${{ matrix.consul_acl }}

      - name: set consul acl default policy (allow/deny)
        id: consul_acl_default_policy
        run: |
          if [ "$test_consul_acl_default_policy" == 'consul_acl_allow' ]
          then
              echo "::set-output name=default_policy::allow"
          else
              echo "::set-output name=default_policy::deny"
          fi
        env:
          test_consul_acl_default_policy: ${{ matrix.consul_acl_default_policy }}

      - name: set nomad acl (enabled/disabled)
        id: nomad_acl
        run: |
          if [ "$test_nomad_acl" == 'nomad_acl_enabled' ]
          then
              echo "::set-output name=nomad_acl::true"
          else
              echo "::set-output name=nomad_acl::false"
          fi
        env:
          test_nomad_acl: ${{ matrix.nomad_acl }}

      - name: set hashicorp binary (oss/enterprise)
        id: hashicorp_binary
        run: |
          if [ "$test_hashicorp_binary" == 'hashicorp_oss' ]
          then
              echo "::set-output name=consul_enterprise::false"
              echo "::set-output name=nomad_enterprise::false"
              echo "::set-output name=vault_enterprise::false"
          else
              echo "::set-output name=consul_enterprise::true"
              echo "::set-output name=nomad_enterprise::true"
              echo "::set-output name=vault_enterprise::true"
          fi
        env:
          test_hashicorp_binary: ${{ matrix.hashicorp_binary }}

      - name: Make .env_override in order to matrix test
        run: python .github/action/create-env.py
        env:
          ENVKEY_env_override: true
          ENVKEY_consul_acl: ${{ steps.consul_acl.outputs.consul_acl }}
          ENVKEY_consul_acl_default_policy: ${{ steps.consul_acl_default_policy.outputs.default_policy }}
          ENVKEY_nomad_acl: ${{ steps.nomad_acl.outputs.nomad_acl }}
          ENVKEY_consul_enterprise: ${{ steps.hashicorp_binary.outputs.consul_enterprise }}
          ENVKEY_nomad_enterprise: ${{ steps.hashicorp_binary.outputs.nomad_enterprise }}
          ENVKEY_vault_enterprise: ${{ steps.hashicorp_binary.outputs.vault_enterprise }}
          FILE_NAME: .env_override

      - name: Run make test
        run: make test
